networks:
  micro_dev:
    driver: bridge

services:
  api_gateway:
    build:
      context: .
      dockerfile: ./crates/api_gateway/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - micro_dev
  # auth_service:
  #   build:
  #     context: .
  #     dockerfile: ./crates/auth_service/Dockerfile
  #   ports:
  #     - "8081:8080"
  #   volumes:
  #     - .:/app
  #   restart: unless-stopped
  #   networks:
  #     - micro_dev

  # project_service:
  #   build:
  #     context: .
  #     dockerfile: ./crates/project_service/Dockerfile
  #   ports:
  #     - "8082:8080"
  #   volumes:
  #     - .:/app
  #   restart: unless-stopped
  #   networks:
  #     - micro_dev