[package]
name = "dev_proto"
version = "0.1.0"
edition = "2024"
build = "build.rs"

# workspace
[dependencies]
tonic.workspace=true
prost.workspace=true
prost-types.workspace=true

# workspace
[build-dependencies]
glob.workspace=true
tonic-build.workspace=true